ALTER TABLE role ADD COLUMN update_time DATETIME NULL;
ALTER TABLE role ADD COLUMN is_deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE role ADD COLUMN deletion_time DATETIME NULL;
ALTER TABLE user_role ADD COLUMN update_time DATETIME NULL;
ALTER TABLE user_role ADD COLUMN is_deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE user_role ADD COLUMN deletion_time DATETIME NULL;